#!/usr/bin/env python3
"""generate_agents.py: derive .claude/agents/<name>.md from the tier map.

The FRONTMATTER (name, description, model, effort, tools, extras) is generated from TIER_MAP.json:
model = ladder[role.rank], effort = role.effort. No alias is hand-written in an agent definition.
The BODY (the agent's charter) is preserved: an existing body under the target file wins; else the
canon body from --bodies/<name>.md; else a one-line placeholder. Standard library only.

Usage:
  python3 memento/tools/generate_agents.py [--map memento/TIER_MAP.json] [--out .claude/agents]
                                           [--bodies memento/agents] [--check]
--check writes nothing and exits 1 if any target differs from what would be generated (doctor use).
"""
import argparse, json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))


def split_frontmatter(text):
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            return text[:end + 4], text[end + 4:].lstrip("\n")
    return "", text


def render(name, spec, m, body):
    role = m["roles"][spec["role"]]
    model = m["ladder"][role["rank"]]
    lines = [f"name: {name}", f"description: {spec['description']}", f"model: {model}"]
    if role.get("effort"): lines.append(f"effort: {role['effort']}")
    if spec.get("tools"): lines.append("tools: " + ", ".join(spec["tools"]))
    for k, v in (spec.get("extra") or {}).items(): lines.append(f"{k}: {v}")
    g = spec.get("guarantees") or {}
    lines.append(f"# generated by memento/tools/generate_agents.py from the tier map (role {spec['role']}, rank {role['rank']}, map verified {m.get('last_verified')}); edit the map, not this block")
    lines.append(f"# guarantees enforced by tool scope: {'; '.join(g.get('enforced') or ['none'])}")
    lines.append(f"# behavioural only (compliance, not a boundary): {'; '.join(g.get('behavioural') or ['none'])}")
    return "---\n" + "\n".join(lines) + "\n---\n" + body.rstrip("\n") + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--map", default=os.environ.get("TIER_MAP") or os.path.join(ROOT, "memento", "TIER_MAP.json"))
    ap.add_argument("--out", default=os.path.join(ROOT, ".claude", "agents"))
    ap.add_argument("--bodies", default=os.path.join(ROOT, "memento", "agents"))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    with open(a.map) as f: raw = json.load(f)
    if raw.get("schema") != 2: sys.exit("tier map is not schema 2 (policy + bindings)")
    binding = os.environ.get("TIER_BINDING", "claude-code"); pol = raw["policy"]; b = raw["bindings"][binding]
    m = {"ladder": b["ladder"], "roles": pol["roles"], "last_verified": pol.get("last_verified"),
         "agents": {n: dict(s_, **b.get("agents", {}).get(n, {})) for n, s_ in pol.get("agents", {}).items()}}
    for n, s_ in m["agents"].items():
        eff = pol["roles"][s_["role"]].get("effort")
        if eff and eff not in b.get("effort_levels", [eff]): sys.exit(f"role effort '{eff}' is not a level the {binding} binding knows")
    drift = 0
    for name, spec in m.get("agents", {}).items():
        target = os.path.join(a.out, name + ".md")
        existing = open(target).read() if os.path.exists(target) else ""
        _, body = split_frontmatter(existing) if existing else ("", "")
        if not body.strip():
            canon = os.path.join(a.bodies, name + ".md")
            body = split_frontmatter(open(canon).read())[1] if os.path.exists(canon) else f"You are {name}. (No charter body found; add one under {a.bodies}/{name}.md.)\n"
        out = render(name, spec, m, body)
        if out != existing:
            drift += 1
            if a.check: print(f"DRIFT  {target}")
            else:
                os.makedirs(a.out, exist_ok=True)
                with open(target, "w") as f: f.write(out)
                print(f"WROTE  {target}  (model={m['ladder'][m['roles'][spec['role']]['rank']]}, effort={m['roles'][spec['role']].get('effort')})")
        elif a.check: print(f"OK     {target}")
    if a.check:
        print(f"generate_agents --check: {drift} file(s) drift from the tier map")
        sys.exit(1 if drift else 0)


if __name__ == "__main__":
    main()
